# Generated by Django 3.2.3 on 2021-06-15 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Производитель')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Этот товар понравился')),
                ('discount', models.IntegerField(verbose_name='')),
                ('new', models.BooleanField(default=False)),
                ('display', models.CharField(max_length=255, verbose_name='Диагональ экрана')),
                ('processor', models.CharField(max_length=255, verbose_name='Процессор')),
                ('video_cart', models.CharField(max_length=255, verbose_name='Параметры видеокарты')),
                ('ram', models.CharField(max_length=20, verbose_name='Оперативная память')),
                ('acum', models.CharField(max_length=255, verbose_name='Время работы от аккамулятора')),
                ('ssd', models.BooleanField(default=False, verbose_name='Наличие ssd диска')),
                ('ssd_info', models.CharField(blank=True, max_length=20, null=True, verbose_name='Объем ssd диска')),
                ('hdd', models.BooleanField(default=False, verbose_name='Наличие hdd диска')),
                ('hdd_info', models.CharField(blank=True, max_length=20, null=True, verbose_name='Объем hdd диска')),
                ('backlight_keyboard', models.BooleanField(default=False, verbose_name='Наличие подсветки клавиатуры')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.brand', verbose_name='Производитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ноутбуки',
            },
        ),
    ]
