# Generated by Django 3.2.3 on 2021-06-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_notebook_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug_brands'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug_category'),
        ),
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('view', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Этот товар понравился')),
                ('discount', models.IntegerField(verbose_name='Скидка')),
                ('new', models.BooleanField(default=False)),
                ('display', models.CharField(max_length=255, verbose_name='Диагональ экрана')),
                ('processor', models.CharField(max_length=255, verbose_name='Процессор')),
                ('ram', models.CharField(max_length=20, verbose_name='Оперативная память')),
                ('acum_value', models.CharField(max_length=255, verbose_name='Объем аккамулятора')),
                ('sd_cart', models.BooleanField(default=True, verbose_name='Наличие sd карты')),
                ('sd_value', models.CharField(max_length=255, verbose_name='Максимальный объем sd карты')),
                ('main_cam_value', models.CharField(max_length=255, verbose_name='Оснавная камера')),
                ('frontal_cam_value', models.CharField(max_length=255, verbose_name='Фронтальная камера')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.brand', verbose_name='Производитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Смартфоны',
            },
        ),
    ]
